version: "3.4"

services:
  gateway:
    hostname: gateway
    container_name: gateway
    image: nginx:1.22.0-alpine
    volumes:
      - ./gateway/_nginx.conf:/etc/nginx/_nginx.conf
      - ./gateway/ssl:/etc/nginx/ssl
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
      API_DOMAIN: ${API_DOMAIN}
      FRONT_DOMAIN: ${FRONT_DOMAIN}
    command: sh -c "envsubst '$$API_DOMAIN $$FRONT_DOMAIN' < /etc/nginx/_nginx.conf > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"
    dns:
      - 172.17.0.1
      - 1.1.1.1
      - 8.8.8.8
    network_mode: bridge
    links:
      #      - api
      - front

  # api:
  #   hostname: api
  #   container_name: api
  #   build:
  #     context: ./api
  #   image: api:1
  #   working_dir: /srv
  #   ## command to keep the container on for remote development
  #   command: bash -c "tail -f /dev/null"
  #   # command: bash -c "cd /srv/app/; yarn develop" #
  #   volumes:
  #     - ./api/:/srv/
  #   # ports:
  #   #   - 1337:1337
  #   dns:
  #     - 172.17.0.1
  #     - 1.1.1.1
  #     - 8.8.8.8
  #   network_mode: bridge
  #   restart: always

  front:
    hostname: front
    container_name: front
    build:
      context: ./front
    image: front:1
    working_dir: /srv
    ## command to keep the container on for remote development
    command: bash -c "tail -f /dev/null"
    #    command: bash -c "yarn develop" #
    volumes:
      - ./front/:/srv/
    ports:
      - 3000:3000
    network_mode: bridge
    dns:
      - 172.17.0.1
      - 1.1.1.1
      - 8.8.8.8
    restart: always
